# sonarqube-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube # Use the namespace created in Step 1 (if applicable)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          ports:
            - containerPort: 9000
          env:
            - name: SONARQUBE_JDBC_USERNAME
              value: sonarqube # Replace with your desired DB username
            - name: SONARQUBE_JDBC_PASSWORD
              value: sonarqube # Replace with your desired DB password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/sonarqube #jdbc:postgresql://sonarqube-postgresql/sonarqube # Replace with your DB connection URL
          volumeMounts:
            - name: sonarqube-pvc
              mountPath: /opt/sonarqube/data
      volumes:
        - name: sonarqube-pvc
          persistentVolumeClaim:
            claimName: sonarqube-pvc
