apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy-template
  namespace: tekton-ci
spec:
  params:
  - name: revision
    description: The Git commit revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-
    spec:
      pipelineRef:
        name: build-deploy
      serviceAccountName: pipeline
      params:
      - name: revision
        value: $(tt.params.revision)
      - name: appGitUrl
        value: https://github.com/HazemFelhi/coffee-shop
      # - name: configGitUrl
      #   value: 'git@github.com:example/app-config.git'
      - name: appImage
        value: docker.io/hazemfelhi/coffee-shop
      workspaces:
      - name: app-source
        emptyDir: {}
      # - name: config-source
      #   emptyDir: {}
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy-binding
  namespace: tekton-ci
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)

---